---
server:
    install: '1'
    packages: [vim, git]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: hermes, ip: 192.168.42.42, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: drupal
mysql:
    install: '1'
    root_password: root
    database: drupal
    user: root
    password: root
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql]
xdebug:
    install: '1'
composer:
    install: '1'

